SET FOREIGN_KEY_CHECKS = 0;
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE `seg_garantias_compra`;
DROP TABLE `seg_soporte_fno`;
DROP TABLE `seg_garantias_compra`;
DROP TABLE `seg_modulos`;
DROP TABLE `seg_rol`;
DROP TABLE `seg_rol_permisos`;
DROP TABLE `seg_rol_usuario`;
DROP TABLE `seg_usuarios_sistema`;
DROP TABLE `ctb_doc`;
DROP TABLE `ctb_factura`;
DROP TABLE `ctb_pgcp`;
DROP TABLE `ctb_libaux`;
DROP TABLE `ctb_retencion_rango`;
DROP TABLE `ctb_causa_retencion`;
DROP TABLE `ctb_causa_costos`;
DROP TABLE `ctt_modalidad`;
DROP TABLE `ctt_adquisiciones`;
DROP TABLE `ctt_bien_servicio`;
DROP TABLE `ctt_adquisicion_detalles`;
DROP TABLE `ctt_clasificacion_bn_sv`;
DROP TABLE `ctt_contratos`;
DROP TABLE `ctt_destino_contrato`;
DROP TABLE `ctt_orden_compra`;
DROP TABLE `ctt_escala_honorarios`;
DROP TABLE `ctt_estado_adq`;
DROP TABLE `ctt_estudios_previos`;
DROP TABLE `ctt_garantias_compra`;
DROP TABLE `ctt_novedad_adicion_prorroga`;
DROP TABLE `ctt_novedad_cesion`;
DROP TABLE `ctt_novedad_liquidacion`;
DROP TABLE `ctt_novedad_suspension`;
DROP TABLE `ctt_novedad_reinicio`;
DROP TABLE `ctt_novedad_terminacion`;
DROP TABLE `tb_polizas`;
DROP TABLE `tb_centrocostos`;
DROP TABLE `tb_tipo_contratacion`;
DROP TABLE `tb_tipo_bien_servicio`;
DROP TABLE `fin_maestro_doc`;
DROP TABLE `fin_respon_doc`;
DROP TABLE `nom_afp`;
DROP TABLE `nom_arl`;
DROP TABLE `nom_cargo_empleado`;
DROP TABLE `nom_causacion`;
DROP TABLE `nom_incremento_salario`;
DROP TABLE `nom_retroactivos`;
DROP TABLE `nom_nominas`;
DROP TABLE `nom_cdp_empleados`;
DROP TABLE `nom_consecutivo_viaticos`;
DROP TABLE `nom_empleado`;
DROP TABLE `nom_contratos_empleados`;
DROP TABLE `nom_sindicatos`;
DROP TABLE `nom_cuota_sindical`;
DROP TABLE `nom_juzgados`;
DROP TABLE `nom_embargos`;
DROP TABLE `nom_empleados_retirados`;
DROP TABLE `nom_epss`;
DROP TABLE `nom_fondo_censan`;
DROP TABLE `nom_horas_ex_trab`;
DROP TABLE `nom_incapacidad`;
DROP TABLE `nom_indemniza_vac`;
DROP TABLE `nom_libranzas`;
DROP TABLE `nom_licencia_luto`;
DROP TABLE `nom_licenciasmp`;
DROP TABLE `nom_licenciasnr`;
DROP TABLE `nom_liq_bsp`;
DROP TABLE `nom_liq_cesantias`;
DROP TABLE `nom_liq_compesatorio`;
DROP TABLE `nom_liq_dias_lab`;
DROP TABLE `nom_liq_dlab_auxt`;
DROP TABLE `nom_liq_embargo`;
DROP TABLE `nom_liq_empleado`;
DROP TABLE `nom_liq_horex`;
DROP TABLE `nom_liq_incap`;
DROP TABLE `nom_liq_indemniza_vac`;
DROP TABLE `nom_liq_libranza`;
DROP TABLE `nom_liq_licluto`;
DROP TABLE `nom_liq_licmp`;
DROP TABLE `nom_liq_licnr`;
DROP TABLE `nom_liq_parafiscales`;
DROP TABLE `nom_liq_prestaciones_sociales`;
DROP TABLE `nom_liq_prima`;
DROP TABLE `nom_liq_prima_nav`;
DROP TABLE `nom_liq_salario`;
DROP TABLE `nom_liq_segsocial_empdo`;
DROP TABLE `nom_liq_sindicato_aportes`;
DROP TABLE `nom_vacaciones`;
DROP TABLE `nom_liq_vac`;
DROP TABLE `nom_nomina_pto_ctb_tes`;
DROP TABLE `nom_novedades_afp`;
DROP TABLE `nom_novedades_arl`;
DROP TABLE `nom_novedades_eps`;
DROP TABLE `nom_novedades_fc`;
DROP TABLE `nom_otros_descuentos`;
DROP TABLE `nom_pago_dependiente`;
DROP TABLE `nom_rango_viaticos`;
DROP TABLE `pto_cdp_detalle`;
DROP TABLE `pto_crp`;
DROP TABLE `pto_crp_detalle`;
DROP TABLE `pto_cop_detalle`;
DROP TABLE `pto_homologa_gastos`;
DROP TABLE `pto_homologa_ingresos`;
DROP TABLE `pto_mod`;
DROP TABLE `pto_mod_detalle`;
DROP TABLE `pto_pag_detalle`;
DROP TABLE `pto_cargue`;
DROP TABLE `pto_presupuestos`;
DROP TABLE `pto_rad`;
DROP TABLE `pto_rad_detalle`;
DROP TABLE `pto_rec`;
DROP TABLE `pto_rec_detalle`;
DROP TABLE `pto_cdp`;
DROP TABLE `nom_rel_rubro`;
DROP TABLE `nom_resolucion_viaticos`;
DROP TABLE `nom_resoluciones`;
DROP TABLE `nom_retencion_fte`;
DROP TABLE `nom_salarios_basico`;
DROP TABLE `nom_soporte_ne`;
DROP TABLE `nom_valxvigencia`;
DROP TABLE `nom_viaticos`;
DROP TABLE `tb_rel_tercero`;
DROP TABLE `tes_cuentas`;
DROP TABLE `tes_caja_const`;
DROP TABLE `tes_caja_doc`;
DROP TABLE `tes_caja_mvto`;
DROP TABLE `tes_caja_respon`;
DROP TABLE `tes_caja_rubros`;
DROP TABLE `tes_causa_arqueo`;
DROP TABLE `tes_conciliacion_detalle`;
DROP TABLE `tes_detalle_pago`;
DROP TABLE `tes_facturador`;
DROP TABLE `tes_rel_pag_cop`;
DROP TABLE `nom_liq_contrato_emp`;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
SET FOREIGN_KEY_CHECKS = 1;
